# Generated by Django 2.2.6 on 2019-10-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
    ]
