# Generated by Django 2.2.6 on 2019-10-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='contacts',
        ),
    ]
